### ISSUE TITLE
mpf crashes on shots.yaml v0.30.25

### ISSUE THREAD

**Issue by mwiz** [missionpinball/mpf-docs#29]
INFO : SwitchController : <<<<< switch: s_left_inlane_e, State:1 >>>>>
ERROR : root : Can't convert 'NoneType' object to str implicitly
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 540, in run
    self._run_loop()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 563, in _run_loop
    self.process_frame()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 575, in process_frame
    self.default_platform.tick(self.clock.frametime)
  File "/usr/local/lib/python3.4/dist-packages/mpf/platforms/fast/fast.py", line 465, in tick
    self.process_received_message(self.receive_queue.get(False))
  File "/usr/local/lib/python3.4/dist-packages/mpf/platforms/fast/fast.py", line 141, in process_received_message
    self.fast_commands[cmd](payload)
  File "/usr/local/lib/python3.4/dist-packages/mpf/platforms/fast/fast.py", line 236, in receive_nw_closed
    platform=self)
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/switch_controller.py", line 249, in process_switch_by_num
    self.process_switch(name=switch.name, state=state, logical=logical)
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/switch_controller.py", line 341, in process_switch
    self._call_handlers(name, state)
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/switch_controller.py", line 400, in _call_handlers
    entry['callback'](**entry['callback_kwargs'])
  File "/usr/local/lib/python3.4/dist-packages/mpf/devices/shot.py", line 486, in hit
    group.hit(mode, profile, state)
  File "/usr/local/lib/python3.4/dist-packages/mpf/devices/shot_group.py", line 136, in hit
    self.machine.events.post(self.name + '_' + profile + '_' + state +
TypeError: Can't convert 'NoneType' object to str implicitly

#config_version=4

shots:
   left_outlane_t:
     switch: s_kickback_t
     show_tokens:
       led: l_left_outlane_t
   left_inlane_e:
     switch: s_left_inlane_e
     show_tokens:
       led: l_left_inlane_e
   right_inlane_c:
     switch: s_right_inlane_c
     show_tokens:
       led: l_right_inlane_c
   right_outlane_h:
     switch: s_right_outlane_h
     #profile: quick_flash
     show_tokens:
       led: l_right_outlane_h

shot_groups:
  tech_lanes:
    shots:
      - left_outlane_t
      - left_inlane_e
      - right_inlane_c
      - right_outlane_h

shot_profiles:
  quick_flash:
    states:
    - name: unlit
      show: off
    - name: hit
      show: quick_flash

shows:
    quick_flash:
       - leds:
           (leds): white
       - leds:
           (leds): off

**Comment by jabdoa2** [comment]
Unfortunately, we cannot reproduce this yet
