### ISSUE TITLE
Doc lin in config_validator.py wrong

### ISSUE THREAD

**Issue by chris20-20** [missionpinball/mpf-docs#291]
Hi,
I just get an error with an wrong link. Could you please check and correct it. Appered because I did something wrong in the config.yaml file.

Using MPF v0.53.2 and VP 10.6.0

Wrong link that is shown:
https://docs.missionpinball.org/en/0.53/logs/CFE-ConfigValidator-6.html

Error message from MPF:
Shutting down...
Event: ======'shutdown'====== Args={}
Shutdown because of an exception:
Runtime Exception
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\program files\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\program files\python36\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\program files\python36\lib\site-packages\mpf\core\device_manager.py", line 114, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "c:\program files\python36\lib\site-packages\mpf\core\mode_controller.py", line 90, in load_mode_devices
    await mode.load_mode_devices()
  File "c:\program files\python36\lib\site-packages\mpf\core\mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "c:\program files\python36\lib\site-packages\mpf\core\device.py", line 104, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\program files\python36\lib\site-packages\mpf\core\config_validator.py", line 281, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "c:\program files\python36\lib\site-packages\mpf\core\config_validator.py", line 328, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\program files\python36\lib\site-packages\mpf\core\config_validator.py", line 757, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\program files\python36\lib\site-packages\mpf\core\config_validator.py", line 477, in _validate_type_machine
    6)
  File "c:\program files\python36\lib\site-packages\mpf\core\config_validator.py", line 776, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:base:shots:rollover_a:switch = "s_top_rollover_a" is not valid. Device s_top_rollover_a of type switches not defined Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/0.53/logs/CFE-ConfigValidator-6.html)
MPF run loop ended.

**Comment by jabdoa2** [comment]
We did not yet create all those pages. Some already exist but there are a lot more left to write.

**Comment by chris20-20** [comment]
Thankx for the answer.
Maybe you create a standard page that says that the page is comming soon, to reduce issues like mine ;-). I think it's a better solution for the meantime.

**Comment by jabdoa2** [comment]
Unfortunately that is easier said than done in Sphinx and readthedocs. I'm not sure if we can somehow redirect all pages inside a directory. Maybe that is possible somehow.

**Comment by jabdoa2** [comment]
I added the sphinx-notfound-page extension and wrote a nice 404 handler. That should fix this issue.
